apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.installedapps'
version = '1.0.0'

def getExtOrDefault(name, defaultValue) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : defaultValue
}

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
if (expoModulesCorePlugin.exists()) {
  apply from: expoModulesCorePlugin
  applyKotlinExpoModulesCorePlugin()
}

android {
  compileSdk getExtOrDefault('compileSdkVersion', 36)

  namespace "expo.modules.installedapps"
  defaultConfig {
    minSdk getExtOrDefault('minSdkVersion', 24)
    targetSdk getExtOrDefault('targetSdkVersion', 36)
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions {
    jvmTarget = "17"
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
